baseURL = "https://nelsontang.github.io/"
languageCode = "zh-cn"
title = "我的技术博客"
theme = "PaperMod"

enableRobotsTXT = true

[params]
  ShowReadingTime = true
  ShowCodeCopyButtons = true
  ShowToc = true
  TocOpen = true

[menu]
  [[menu.main]]
    name = "文章"
    url = "/posts/"
    weight = 1
  [[menu.main]]
    name = "标签"
    url = "/tags/"
    weight = 2
  [[menu.main]]
    name = "归档"
    url = "/archives/"
    weight = 3
